name: fashion_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  country_picker: ^2.0.27
  flutter_otp_text_field: ^1.5.1+1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/product.json

 
  fonts:
    - family: Golos
      fonts:
        - asset: assets/fonts/GolosText/GolosText-Regular.ttf
          weight: 500
        - asset: assets/fonts/GolosText/GolosText-Bold.ttf
          weight: 700
        - asset: assets/fonts/GolosText/GolosText-Medium.ttf
          weight: 400
        - asset: assets/fonts/GolosText/GolosText-Black.ttf
        - asset: assets/fonts/GolosText/GolosText-SemiBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

